### ISSUE TITLE
Utility Landspage missing many colorless utility lands

### ISSUE THREAD

**Issue by Delightfulgiraffe** [starkat99/manabase#5]
thespian stage, Mycosynth Gardens, eye of ugin, Maze's end, springjack pasture, Treasure map, thaumatic compas, bonder's enclave, bazaar of baghdad, forge of heroes, Hall of Tagsin (it is the only card tagged utility, rather than utility land), Maze ofith, Maze of shadows, Oasis, Phyrexia's Core, Terrain Generator, sea gate wreckage

These are theones i noticed are missing, there may be more

Sea Gate Wreckage is not listed anywhere on the website

**Comment by VoidStarKat** [comment]
Thanks, I've fixed all of this now
